variables:
    TUTOR_PLUGIN: vahana
    TUTOR_PYPI_PACKAGE: vahana-learning-indigo-theme
    TUTOR_BUILD_IMAGE: openedx
    OPENEDX_RELEASE: palm
    GITHUB_REPO: decimal-vinay/vahana-learning-indigo-theme

include:
  - project: 'community/tutor-ci'
    file: 'plugin-gitlab-ci.yml'
